import { useMemo, useState } from 'react';
import { assess, createHap, evidenceForFinding, getAssessmentPlan, SKIPPED_ANSWER, type AnswerValue, type Answers } from '@jaanch/core';

const priorityLabel = { essential: 'High assessment priority', recommended: 'Recommended', optional: 'Optional' } as const;

export default function App(){
 const [answers,setAnswers]=useState<Answers>({}); const [done,setDone]=useState(false); const [currentId,setCurrentId]=useState<string>(); const [history,setHistory]=useState<string[]>([]);
 const plan=useMemo(()=>getAssessmentPlan(answers),[answers]); const current=plan.questions.find(item=>item.question.id===currentId) ?? plan.nextQuestion; const q=current?.question; const result=useMemo(()=>assess(answers),[answers]);
 const setCurrent=(id:string,v:AnswerValue)=>{setCurrentId(id);setAnswers(a=>({...a,[id]:v}));};
 const toggleMulti=(id:string,v:string)=>{setCurrentId(id);setAnswers(a=>{const existing=Array.isArray(a[id])?a[id] as string[]:[]; return {...a,[id]:existing.includes(v)?existing.filter(x=>x!==v):[...existing,v]};});};
 const advance=()=>{if(!q)return; const next=plan.nextQuestion; if(!next){setDone(true);return;} setHistory(h=>[...h,q.id]); setCurrentId(next.question.id);};
 const skip=()=>{if(!q)return; setHistory(h=>[...h,q.id]); setAnswers(a=>({...a,[q.id]:SKIPPED_ANSWER})); setCurrentId(undefined);};
 const back=()=>setHistory(h=>{const copy=[...h]; const previous=copy.pop(); if(previous)setCurrentId(previous); return copy;});
 if(done || (plan.complete && !currentId)) return <main><h1>Your Health Map</h1><p>Evidence completeness: {result.evidenceCompleteness}%</p>{result.redFlags.map(x=><aside key={x}>{x}</aside>)}{result.findings.map(f=>{const ev=evidenceForFinding(result.evidenceGraph,f); return <section key={f.id}><h2>{f.title}</h2><p><b>{f.status}</b> · confidence {f.confidence} · {f.evidenceLevel}</p><p>{f.summary}</p><details><summary>Why this finding</summary>{ev.supporting.length>0&&<><h3>Supporting evidence</h3><ul>{ev.supporting.map(n=><li key={n.id}>{n.label}: {n.detail}</li>)}</ul></>}{ev.contradicting.length>0&&<><h3>Contradicting evidence</h3><ul>{ev.contradicting.map(n=><li key={n.id}>{n.label}: {n.detail}</li>)}</ul></>}{ev.missing.length>0&&<><h3>Missing evidence</h3><ul>{ev.missing.map(n=><li key={n.id}>{n.label}: {n.detail}</li>)}</ul></>}<small>Rule {f.ruleId}@{f.ruleVersion}</small></details><p>{f.actions[0]}</p></section>})}<section><h2>What to check next</h2><p><small>Priority here means priority for reducing assessment uncertainty, not a diagnosis or medical-necessity order.</small></p>{result.testPlan.blockedReason?<aside>{result.testPlan.blockedReason}</aside>:<>{result.testPlan.minimalSetIds.length?<ol>{result.testPlan.recommendations.filter(r=>r.selectedForMinimalSet).map(r=><li key={r.id}><b>{r.title}</b> — {priorityLabel[r.priority]}<br/><span>{r.rationale}</span><br/><small>{r.maturity} mapping</small></li>)}</ol>:<p>No mapped investigation is currently needed to resolve known evidence gaps.</p>}{result.testPlan.recommendations.some(r=>!r.selectedForMinimalSet)&&<details><summary>Alternatives / additional options</summary><ul>{result.testPlan.recommendations.filter(r=>!r.selectedForMinimalSet).map(r=><li key={r.id}><b>{r.title}</b> — {r.rationale}</li>)}</ul></details>}{result.testPlan.uncoveredEvidenceIds.length>0&&<p><small>Unmapped evidence gaps: {result.testPlan.uncoveredEvidenceIds.join(', ')}</small></p>}</>}</section><details><summary>HAP-1.0</summary><pre>{JSON.stringify(createHap(answers,result),null,2)}</pre></details></main>;
 if(!q || !current) return <main><h1>Jaanch</h1><p>No questions available.</p></main>;
 const value=answers[q.id];
 return <main><header><h1>Jaanch</h1><p>Deterministic personal health assessment</p></header><progress value={plan.answered} max={Math.max(plan.questions.length,1)}/><section><small>{q.master?'Master question':'Adaptive follow-up'} · {q.domain}</small><h2>{q.title}</h2>{q.type==='number'?<input type="number" min={q.min} max={q.max} value={typeof value==='number'?value:''} onChange={e=>setCurrent(q.id,Number(e.target.value))}/>:<div>{q.options?.map(o=>{const selected=q.type==='multi'?Array.isArray(value)&&value.includes(o.value):value===(q.type==='boolean'?(o.value==='yes'):o.value); return <button aria-pressed={selected} key={o.value} onClick={()=>q.type==='multi'?toggleMulti(q.id,o.value):setCurrent(q.id,q.type==='boolean'?o.value==='yes':o.value)}>{selected?'✓ ':''}{o.label}</button>})}</div>}<p><strong>Why asked:</strong> {current.whyAsked.join(' ')}</p></section><nav><button disabled={!history.length} onClick={back}>Back</button><button onClick={skip}>Skip / don't know</button><button disabled={value===undefined || (Array.isArray(value)&&value.length===0)} onClick={advance}>Continue</button></nav></main>;
}
