import { useMemo, useState } from 'react';
import { assess, buildHealthMapViewModel, createHap, getAssessmentPlan, SKIPPED_ANSWER, type AnswerValue, type Answers } from '@jaanch/core';

export default function App(){
 const [answers,setAnswers]=useState<Answers>({}); const [done,setDone]=useState(false); const [currentId,setCurrentId]=useState<string>(); const [history,setHistory]=useState<string[]>([]);
 const plan=useMemo(()=>getAssessmentPlan(answers),[answers]); const current=plan.questions.find(item=>item.question.id===currentId) ?? plan.nextQuestion; const q=current?.question; const result=useMemo(()=>assess(answers),[answers]); const healthMap=useMemo(()=>buildHealthMapViewModel(result),[result]);
 const setCurrent=(id:string,v:AnswerValue)=>{setCurrentId(id);setAnswers(a=>({...a,[id]:v}));};
 const toggleMulti=(id:string,v:string)=>{setCurrentId(id);setAnswers(a=>{const existing=Array.isArray(a[id])?a[id] as string[]:[]; return {...a,[id]:existing.includes(v)?existing.filter(x=>x!==v):[...existing,v]};});};
 const advance=()=>{if(!q)return; const next=plan.nextQuestion; if(!next){setDone(true);return;} setHistory(h=>[...h,q.id]); setCurrentId(next.question.id);};
 const skip=()=>{if(!q)return; setHistory(h=>[...h,q.id]); setAnswers(a=>({...a,[q.id]:SKIPPED_ANSWER})); setCurrentId(undefined);};
 const back=()=>setHistory(h=>{const copy=[...h]; const previous=copy.pop(); if(previous)setCurrentId(previous); return copy;});
 if(done || (plan.complete && !currentId)) return <main><header><h1>{healthMap.title}</h1><p>{healthMap.evidence.label}</p></header>{healthMap.urgentMessages.map(x=><aside key={x}><b>Urgent:</b> {x}</aside>)}<section><h2>Top priorities</h2>{healthMap.topPriorities.length?<ol>{healthMap.topPriorities.map(x=><li key={x.id}><b>{x.title}</b><br/>{x.detail}</li>)}</ol>:<p>No high-priority item from the current evidence.</p>}</section><section><h2>Safety context</h2>{healthMap.safety.flags.map(x=><article key={x.id}><b>{x.label}</b> · {x.severityLabel}<p>{x.reason}</p></article>)}{healthMap.safety.clearLabel&&<p>{healthMap.safety.clearLabel}</p>}{healthMap.safety.restrictions.length>0&&<ul>{healthMap.safety.restrictions.map(x=><li key={x.actionClass}><b>{x.actionLabel}</b> — {x.dispositionLabel}{x.reasons[0]?`: ${x.reasons[0]}`:''}</li>)}</ul>}</section>{healthMap.findings.map(f=><section key={f.id}><h2>{f.domainLabel}: {f.title}</h2><p><b>{f.statusLabel}</b> · {f.urgencyLabel} · {f.confidenceLabel} · {f.evidenceLevelLabel}</p><p>{f.summary}</p><details><summary>Why this finding</summary>{f.supporting.length>0&&<><h3>Supports</h3><ul>{f.supporting.map(x=><li key={x.id}>{x.label}: {x.detail}</li>)}</ul></>}{f.contradicting.length>0&&<><h3>Contradicts</h3><ul>{f.contradicting.map(x=><li key={x.id}>{x.label}: {x.detail}</li>)}</ul></>}{f.missing.length>0&&<><h3>Missing</h3><ul>{f.missing.map(x=><li key={x.id}>{x.label}: {x.detail}</li>)}</ul></>}<small>{f.ruleLabel}</small></details>{f.action&&<p>{f.action}</p>}</section>)}<section><h2>What to check next</h2><p><small>{healthMap.investigations.disclaimer}</small></p>{healthMap.investigations.blockedReason?<aside>{healthMap.investigations.blockedReason}</aside>:<>{healthMap.investigations.minimal.length?<ol>{healthMap.investigations.minimal.map(x=><li key={x.id}><b>{x.title}</b> — {x.priorityLabel}<br/>{x.rationale}<br/><small>{x.maturityLabel} · {x.sourceIds.join(', ')}</small></li>)}</ol>:<p>{healthMap.investigations.emptyLabel}</p>}{healthMap.investigations.alternatives.length>0&&<details><summary>Alternatives / additional options</summary><ul>{healthMap.investigations.alternatives.map(x=><li key={x.id}><b>{x.title}</b> — {x.rationale}</li>)}</ul></details>}</>}</section><details><summary>Clinical governance</summary><p>{healthMap.governance.label}</p><p>Sources: {healthMap.governance.referencedSourceIds.join(', ')}</p><p>Prototype rules: {healthMap.governance.prototypeRuleIds.join(', ') || 'None'}</p></details><details><summary>HAP-1.0</summary><pre>{JSON.stringify(createHap(answers,result),null,2)}</pre></details></main>;
 if(!q || !current) return <main><h1>Jaanch</h1><p>No questions available.</p></main>;
 const value=answers[q.id];
 return <main><header><h1>Jaanch</h1><p>Deterministic personal health assessment</p></header><progress value={plan.answered} max={Math.max(plan.questions.length,1)}/><section><small>{q.master?'Master question':'Adaptive follow-up'} · {q.domain}</small><h2>{q.title}</h2>{q.description&&<p>{q.description}</p>}{q.type==='number'?<input type="number" min={q.min} max={q.max} value={typeof value==='number'?value:''} onChange={e=>setCurrent(q.id,Number(e.target.value))}/>:<div>{q.options?.map(o=>{const selected=q.type==='multi'?Array.isArray(value)&&value.includes(o.value):value===(q.type==='boolean'?(o.value==='yes'):o.value); return <button aria-pressed={selected} key={o.value} onClick={()=>q.type==='multi'?toggleMulti(q.id,o.value):setCurrent(q.id,q.type==='boolean'?o.value==='yes':o.value)}>{selected?'✓ ':''}{o.label}</button>})}</div>}<p><strong>Why asked:</strong> {current.whyAsked.join(' ')}</p></section><nav><button disabled={!history.length} onClick={back}>Back</button><button onClick={skip}>Skip / don't know</button><button disabled={value===undefined || (Array.isArray(value)&&value.length===0)} onClick={advance}>Continue</button></nav></main>;
}
