import { createJaanchProfile, type JaanchProfile } from './profile';
import { emptyAssessmentCaptureContext, type AssessmentCaptureContext } from './intake';
import type { Answers, LabMarkerId, LabRecord } from './types';

function isoDaysAgo(asOf:Date,days:number){const date=new Date(asOf);date.setUTCDate(date.getUTCDate()-days);return date.toISOString();}
function lab(asOf:Date,id:string,markerId:LabMarkerId,value:number,unit:string,daysAgo=30):LabRecord{return{id,markerId,value,unit,collectedAt:isoDaysAgo(asOf,daysAgo),source:'import',verification:'user_confirmed',sourceLabel:'Jaanch mock profile'};}
function context(patch?:Partial<AssessmentCaptureContext>):AssessmentCaptureContext{
 const base=emptyAssessmentCaptureContext();
 return {...base,...patch,activity:{...base.activity,...patch?.activity},recordedMeasurements:patch?.recordedMeasurements??base.recordedMeasurements,medications:patch?.medications??base.medications,supplements:patch?.supplements??base.supplements,familyHistory:patch?.familyHistory??base.familyHistory,customConditions:patch?.customConditions??base.customConditions,customConcerns:patch?.customConcerns??base.customConcerns,customFamilyHistory:patch?.customFamilyHistory??base.customFamilyHistory};
}
const baseAnswers=(overrides:Answers={}):Answers=>({age:37,sex:'male',heightCm:175,weightKg:70,waistCm:84,diagnosedConditions:['none'],prescriptionMedications:false,supplementUse:false,medicationOrSupplementAllergy:false,currentConcerns:['none'],diet:'vegetarian',sleepHours:7.5,smoking:false,recentLabs:true,...overrides});

export function getMockProfiles(asOf=new Date()):JaanchProfile[]{
 const generatedAt=asOf.toISOString();
 return [
  createJaanchProfile({id:'mock-healthy-active',name:'Mock — active adult with reassuring measured evidence',description:'Exercises the quiet/monitor path with eligible glycemic, lipid, B12 and iron evidence.',createdAt:generatedAt,answers:baseAnswers({activityDays:6}),capturedContext:context({activity:{walkingDaysPerWeek:6,walkingMinutesPerDay:45,walkingPace:'brisk',exerciseTypes:['strength'],exerciseDaysPerWeek:2,exerciseMinutesPerSession:40,exerciseIntensity:'moderate'}}),labs:[lab(asOf,'mock-hba1c','hba1c',5.3,'%',28),lab(asOf,'mock-fpg','fasting_glucose',89,'mg/dL',28),lab(asOf,'mock-b12','vitamin_b12',430,'pg/mL',28),lab(asOf,'mock-ldl','ldl',104,'mg/dL',28),lab(asOf,'mock-hdl','hdl',52,'mg/dL',28),lab(asOf,'mock-tg','triglycerides',110,'mg/dL',28),lab(asOf,'mock-tc','total_cholesterol',178,'mg/dL',28),lab(asOf,'mock-hgb','hemoglobin',14.2,'g/dL',28),lab(asOf,'mock-ferritin','ferritin',62,'ng/mL',28)]}),

  createJaanchProfile({id:'mock-cardiometabolic-risk',name:'Mock — cardiometabolic risk + dyslipidemia',description:'Higher waist/inactivity plus prediabetes-range HbA1c and elevated LDL/triglycerides.',createdAt:generatedAt,answers:baseAnswers({age:52,heightCm:172,weightKg:88,waistCm:104,activityDays:1,familyDiabetes:true,diet:'mixed'}),capturedContext:context({familyHistory:['diabetes','premature_cvd'],activity:{walkingDaysPerWeek:1,walkingMinutesPerDay:20,exerciseTypes:[],exerciseDaysPerWeek:0,exerciseMinutesPerSession:0}}),labs:[lab(asOf,'risk-hba1c','hba1c',6.1,'%',20),lab(asOf,'risk-fpg','fasting_glucose',114,'mg/dL',20),lab(asOf,'risk-ldl','ldl',172,'mg/dL',20),lab(asOf,'risk-hdl','hdl',38,'mg/dL',20),lab(asOf,'risk-tg','triglycerides',280,'mg/dL',20),lab(asOf,'risk-tc','total_cholesterol',258,'mg/dL',20),lab(asOf,'risk-hgb','hemoglobin',14.8,'g/dL',20),lab(asOf,'risk-ferritin','ferritin',95,'ng/mL',20)]}),

  createJaanchProfile({id:'mock-vegetarian-b12-iron',name:'Mock — vegetarian with low B12 + anemia/iron evidence',description:'Exercises B12 and iron clinician-review paths while Vitamin D stays recorded/unassessed.',createdAt:generatedAt,answers:baseAnswers({age:36,sex:'female',reproductiveContext:'none',heightCm:162,weightKg:58,waistCm:76,currentConcerns:['fatigue'],diet:'vegetarian'}),capturedContext:context({supplements:[{id:'mock-supp-d',name:'Vitamin D',category:'vitamin_d',state:'recorded_unassessed'}],recordedMeasurements:[{id:'mock-vitd',markerId:'vitamin_d_25oh',label:'Vitamin D (25-OH)',value:'18',unit:'ng/mL',collectedAt:isoDaysAgo(asOf,18).slice(0,10),source:'import',verification:'user_confirmed',state:'recorded_unassessed'}]}),labs:[lab(asOf,'veg-b12','vitamin_b12',168,'pg/mL',18),lab(asOf,'veg-hgb','hemoglobin',10.8,'g/dL',18),lab(asOf,'veg-ferritin','ferritin',9,'ng/mL',18)]}),

  createJaanchProfile({id:'mock-treated-context',name:'Mock — treated lipid/BP context',description:'Shows that medicines and a BP reading are retained, while one BP reading remains unassessed in M13.4.',createdAt:generatedAt,answers:baseAnswers({age:58,diagnosedConditions:['hypertension','lipid_disorder'],prescriptionMedications:true,diet:'vegetarian'}),capturedContext:context({medications:[{id:'mock-atorvastatin',name:'Atorvastatin',category:'lipid_lowering',purpose:'Cholesterol',state:'recorded_unassessed'},{id:'mock-amlodipine',name:'Amlodipine',category:'blood_pressure',purpose:'Blood pressure',state:'recorded_unassessed'}],recordedMeasurements:[{id:'mock-bp',markerId:'blood_pressure',label:'Blood pressure',value:'138/86',unit:'mmHg',collectedAt:isoDaysAgo(asOf,5).slice(0,10),source:'import',verification:'user_confirmed',state:'recorded_unassessed'}]}),labs:[lab(asOf,'treated-ldl','ldl',82,'mg/dL',25),lab(asOf,'treated-hdl','hdl',48,'mg/dL',25),lab(asOf,'treated-tg','triglycerides',135,'mg/dL',25),lab(asOf,'treated-tc','total_cholesterol',158,'mg/dL',25),lab(asOf,'treated-hgb','hemoglobin',13.9,'g/dL',25),lab(asOf,'treated-ferritin','ferritin',72,'ng/mL',25)]}),

  createJaanchProfile({id:'mock-severe-lipid-signal',name:'Mock — severe LDL signal',description:'Exercises the bounded clinician-review path for LDL-C at or above 190 mg/dL.',createdAt:generatedAt,answers:baseAnswers({age:44,diet:'mixed'}),capturedContext:context({familyHistory:['lipid_disorder']}),labs:[lab(asOf,'severe-ldl','ldl',208,'mg/dL',12),lab(asOf,'severe-hdl','hdl',45,'mg/dL',12),lab(asOf,'severe-tg','triglycerides',165,'mg/dL',12),lab(asOf,'severe-tc','total_cholesterol',286,'mg/dL',12)]}),

  createJaanchProfile({id:'mock-unassessed-thyroid-vitd',name:'Mock — thyroid + Vitamin D retained but unassessed',description:'A boundary fixture: TSH and Vitamin D are intentionally recorded context, not interpreted by M13.4.',createdAt:generatedAt,answers:baseAnswers({age:40,currentConcerns:['fatigue','skin_hair']}),capturedContext:context({recordedMeasurements:[{id:'mock-tsh',markerId:'tsh',label:'TSH',value:'8.2',unit:'mIU/L',collectedAt:isoDaysAgo(asOf,15).slice(0,10),source:'import',verification:'user_confirmed',state:'recorded_unassessed'},{id:'mock-vitd-low',markerId:'vitamin_d_25oh',label:'Vitamin D (25-OH)',value:'16',unit:'ng/mL',collectedAt:isoDaysAgo(asOf,15).slice(0,10),source:'import',verification:'user_confirmed',state:'recorded_unassessed'}]}),labs:[lab(asOf,'boundary-hgb','hemoglobin',13.7,'g/dL',15),lab(asOf,'boundary-ferritin','ferritin',48,'ng/mL',15)]}),
 ];
}

export function mockProfile(id:string,asOf=new Date()){
 return getMockProfiles(asOf).find((profile)=>profile.id===id);
}
