import type { Question } from './types';

const yesNo = [{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }];

export const questions: Question[] = [
  { id: 'age', domain: 'baseline', priority: 1, title: 'What is your age?', type: 'number', min: 1, max: 110, master: true },
  { id: 'sex', domain: 'baseline', priority: 2, title: 'Sex at birth', type: 'single', master: true, options: [{value:'female',label:'Female'},{value:'male',label:'Male'},{value:'other',label:'Other / intersex'},{value:'prefer_not',label:'Prefer not to say'}] },
  { id: 'reproductiveContext', domain: 'baseline', priority: 2.5, title: 'Pregnancy / breastfeeding context', type: 'single', master: true, showWhen: [{questionId:'sex',operator:'eq',value:'female'}], options: [{value:'none',label:'Not pregnant / breastfeeding'},{value:'pregnant',label:'Pregnant'},{value:'trying',label:'Trying to conceive'},{value:'breastfeeding',label:'Breastfeeding'},{value:'unsure',label:'Unsure'}] },
  { id: 'heightCm', domain: 'baseline', priority: 3, title: 'Height', type: 'number', unit: 'cm', min: 80, max: 230, master: true },
  { id: 'weightKg', domain: 'baseline', priority: 4, title: 'Weight', type: 'number', unit: 'kg', min: 15, max: 350, master: true },
  { id: 'waistCm', domain: 'baseline', priority: 5, title: 'Waist circumference', type: 'number', unit: 'cm', min: 35, max: 200, master: true },
  { id: 'diagnosedConditions', domain: 'baseline', priority: 6, title: 'Which diagnosed conditions do you have?', type: 'multi', master: true, options: [{value:'diabetes',label:'Diabetes'},{value:'prediabetes',label:'Prediabetes'},{value:'hypertension',label:'High blood pressure'},{value:'kidney',label:'Kidney disease'},{value:'liver',label:'Liver disease'},{value:'heart',label:'Heart / vascular disease'},{value:'none',label:'None / not diagnosed'}] },
  { id: 'kidneyDiseaseSeverity', domain: 'baseline', priority: 6.1, title: 'How would you describe your kidney disease?', type: 'single', showWhen: [{questionId:'diagnosedConditions',operator:'includes',value:'kidney'}], options: [{value:'early_unknown',label:'Early stage / not sure'},{value:'stage3',label:'Stage 3'},{value:'stage4_5',label:'Stage 4–5'},{value:'dialysis',label:'On dialysis'},{value:'transplant',label:'Kidney transplant'}] },
  { id: 'liverDiseaseSeverity', domain: 'baseline', priority: 6.2, title: 'How would you describe your liver disease?', type: 'single', showWhen: [{questionId:'diagnosedConditions',operator:'includes',value:'liver'}], options: [{value:'mild_unknown',label:'Mild / not sure'},{value:'chronic',label:'Chronic liver disease'},{value:'cirrhosis',label:'Cirrhosis'},{value:'decompensated',label:'Decompensated / complications'},{value:'transplant',label:'Liver transplant'}] },
  { id: 'prescriptionMedications', domain: 'baseline', priority: 6.5, title: 'Do you currently take prescription medicines?', type: 'boolean', options: yesNo, master: true },
  { id: 'medicationCount', domain: 'baseline', priority: 6.6, title: 'About how many prescription medicines do you take regularly?', type: 'number', min: 0, max: 40, showWhen: [{questionId:'prescriptionMedications',operator:'eq',value:true}] },
  { id: 'medicationCategories', domain: 'baseline', priority: 6.7, title: 'Which medicine categories apply?', type: 'multi', showWhen: [{questionId:'prescriptionMedications',operator:'eq',value:true}], options: [{value:'anticoagulant',label:'Blood thinner / anticoagulant'},{value:'diabetes',label:'Diabetes medicine'},{value:'metformin',label:'Metformin'},{value:'blood_pressure',label:'Blood-pressure medicine'},{value:'thyroid',label:'Thyroid medicine'},{value:'steroid',label:'Long-term steroid'},{value:'ppi',label:'Acid-reducing medicine / PPI'},{value:'psychiatric',label:'Psychiatric medicine'},{value:'other',label:'Other'}] },
  { id: 'supplementUse', domain: 'baseline', priority: 6.8, title: 'Do you currently take vitamins, minerals or herbal supplements?', type: 'boolean', options: yesNo, master: true },
  { id: 'supplementCategories', domain: 'baseline', priority: 6.9, title: 'Which supplements do you currently take?', type: 'multi', showWhen: [{questionId:'supplementUse',operator:'eq',value:true}], options: [{value:'multivitamin',label:'Multivitamin'},{value:'vitamin_d',label:'Vitamin D'},{value:'b12',label:'Vitamin B12'},{value:'iron',label:'Iron'},{value:'calcium',label:'Calcium'},{value:'herbal',label:'Herbal / traditional product'},{value:'other',label:'Other'}] },
  { id: 'medicationOrSupplementAllergy', domain: 'baseline', priority: 6.95, title: 'Have you had a known allergy or severe reaction to a medicine or supplement?', type: 'boolean', options: yesNo, master: true },
  { id: 'diet', domain: 'baseline', priority: 7, title: 'Which best describes your usual diet?', type: 'single', master: true, options: [{value:'vegan',label:'Vegan'},{value:'vegetarian',label:'Vegetarian'},{value:'eggetarian',label:'Vegetarian + eggs'},{value:'mixed',label:'Mixed / omnivore'}] },
  { id: 'activityDays', domain: 'baseline', priority: 8, title: 'On how many days per week do you exercise for at least 30 minutes?', type: 'number', unit: 'days/week', min: 0, max: 7, master: true },
  { id: 'sleepHours', domain: 'baseline', priority: 9, title: 'How many hours do you usually sleep?', type: 'number', unit: 'hours/night', min: 2, max: 14, master: true },
  { id: 'smoking', domain: 'baseline', priority: 10, title: 'Do you currently smoke or use tobacco?', type: 'boolean', options: yesNo, master: true },
  { id: 'familyDiabetes', domain: 'baseline', priority: 11, title: 'Does a parent or sibling have diabetes?', type: 'boolean', options: yesNo, master: true },
  { id: 'currentConcerns', domain: 'baseline', priority: 12, title: 'What are your current health concerns?', type: 'multi', master: true, options: [{value:'fatigue',label:'Fatigue'},{value:'sleep',label:'Poor sleep'},{value:'tingling',label:'Tingling / numbness'},{value:'chestPain',label:'Chest pain / pressure'},{value:'thirst',label:'Excess thirst / urination'},{value:'none',label:'No current concerns'}] },
  { id: 'recentLabs', domain: 'baseline', priority: 13, title: 'Do you have blood tests from the last 12 months?', type: 'boolean', options: yesNo, master: true, description: 'Lab values are entered separately with unit, collection date and verification so they cannot bypass evidence checks.' },
  { id: 'frailtyConcerns', domain: 'baseline', priority: 14, title: 'Do you have significant frailty, recurrent falls, or need help with usual daily activities?', type: 'boolean', options: yesNo, master: true, showWhen: [{questionId:'age',operator:'gte',value:65}] },
  { id: 'snoring', domain: 'sleep', priority: 40, title: 'Do you snore loudly or wake unrefreshed?', type: 'boolean', options: yesNo, showWhen: [{questionId:'currentConcerns',operator:'includes',value:'sleep'}] },
  { id: 'redFlagChestPain', domain: 'safety', priority: 1, title: 'Is chest pain severe, new, or associated with breathlessness, fainting, sweating, or pain spreading to the arm/jaw?', type: 'boolean', options: yesNo, showWhen: [{questionId:'currentConcerns',operator:'includes',value:'chestPain'}] }
];
