import { assertAIReviewVerification } from './verificationAI';
import { assertCoreVerification } from './verification';
import { assertIntakeVerification } from './verificationIntake';
import { assertEvidenceCaptureVerification } from './verificationEvidenceCapture';
import { assertClinicalExpansionVerification } from './verificationClinicalExpansion';
import { assertPresentationVerification } from './verificationPresentation';
import { assertRecommendationVerification } from './verificationRecommendations';
import { assertLongitudinalVerification } from './verificationLongitudinal';

const core = assertCoreVerification();
const intake = assertIntakeVerification();
const evidenceCapture = assertEvidenceCaptureVerification();
const clinicalExpansion = assertClinicalExpansionVerification();
const presentation = assertPresentationVerification();
const recommendations = assertRecommendationVerification();
const longitudinal = assertLongitudinalVerification();
const ai = assertAIReviewVerification();
const all = [...core, ...intake, ...evidenceCapture, ...clinicalExpansion, ...presentation, ...recommendations, ...longitudinal, ...ai];
for (const result of all) console.log('PASS ' + result.id);
console.log('Verification passed: ' + all.length + '/' + all.length);
