import { assertAIReviewVerification } from './verificationAI';
import { assertAIReviewV2Verification } from './verificationAIV2';
import { assertCoreVerification } from './verification';
import { assertIntakeVerification } from './verificationIntake';
import { assertEvidenceCaptureVerification } from './verificationEvidenceCapture';
import { assertPresentationVerification } from './verificationPresentation';
import { assertRecommendationVerification } from './verificationRecommendations';
import { assertLongitudinalVerification } from './verificationLongitudinal';
import { assertClinicalExpansionVerification } from './verificationClinicalExpansion';
import { assertProfileVerification } from './verificationProfiles';
import { assertPersistenceVerification } from './verificationPersistence';
import { assertConsumerValueVerification } from './verificationConsumerValue';

const core = assertCoreVerification();
const intake = assertIntakeVerification();
const evidenceCapture = assertEvidenceCaptureVerification();
const clinicalExpansion = assertClinicalExpansionVerification();
const profiles = assertProfileVerification();
const persistence = assertPersistenceVerification();
const presentation = assertPresentationVerification();
const recommendations = assertRecommendationVerification();
const longitudinal = assertLongitudinalVerification();
const ai = assertAIReviewVerification();
const aiV2 = assertAIReviewV2Verification();
const consumerValue = assertConsumerValueVerification();
const all = [...core, ...intake, ...evidenceCapture, ...clinicalExpansion, ...profiles, ...persistence, ...presentation, ...recommendations, ...longitudinal, ...ai, ...aiV2, ...consumerValue];
for (const result of all) console.log('PASS ' + result.id);
console.log('Verification passed: ' + all.length + '/' + all.length);
