import { useMemo, useState } from 'react';
import { SafeAreaView, ScrollView, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { assess, getAssessmentPlan, SKIPPED_ANSWER, type AnswerValue, type Answers } from '@jaanch/core';

export default function App(){
 const [answers,setAnswers]=useState<Answers>({}); const [done,setDone]=useState(false);
 const plan=useMemo(()=>getAssessmentPlan(answers),[answers]); const current=plan.nextQuestion; const q=current?.question; const result=useMemo(()=>assess(answers),[answers]);
 const set=(id:string,v:AnswerValue)=>setAnswers(a=>({...a,[id]:v}));
 const toggleMulti=(id:string,v:string)=>setAnswers(a=>{const existing=Array.isArray(a[id])?a[id] as string[]:[]; return {...a,[id]:existing.includes(v)?existing.filter(x=>x!==v):[...existing,v]};});
 if(done || plan.complete) return <SafeAreaView style={{flex:1}}><ScrollView contentContainerStyle={{padding:24,gap:16}}><Text style={{fontSize:34,fontWeight:'700'}}>Your Health Map</Text><Text>Evidence completeness {result.evidenceCompleteness}%</Text>{result.redFlags.map(x=><View key={x} style={{padding:16,backgroundColor:'#fee2e2'}}><Text>{x}</Text></View>)}{result.findings.map(f=><View key={f.id} style={{padding:18,borderWidth:1,borderColor:'#ddd',borderRadius:16}}><Text style={{fontWeight:'700',fontSize:20}}>{f.title}</Text><Text>{f.status}</Text><Text>{f.summary}</Text><Text>{f.actions[0]}</Text></View>)}</ScrollView></SafeAreaView>;
 if(!q || !current) return null; const value=answers[q.id];
 return <SafeAreaView style={{flex:1}}><ScrollView contentContainerStyle={{padding:24,gap:18}}><Text style={{fontSize:30,fontWeight:'800'}}>Jaanch</Text><Text>{plan.answered} answered · {plan.remaining} remaining</Text><Text style={{fontSize:26,fontWeight:'700'}}>{q.title}</Text><Text>{q.master?'Master question':'Adaptive follow-up'} · {q.domain}</Text>{q.type==='number'?<TextInput keyboardType="numeric" value={typeof value==='number'?String(value):''} onChangeText={text=>{const n=Number(text); if(text!==''&&!Number.isNaN(n))set(q.id,n)}} style={{padding:16,borderWidth:1,borderColor:'#bbb',borderRadius:14}}/>:q.options?.map(o=>{const selected=q.type==='multi'?Array.isArray(value)&&value.includes(o.value):value===(q.type==='boolean'?(o.value==='yes'):o.value); return <TouchableOpacity key={o.value} style={{padding:16,borderWidth:1,borderColor:selected?'#111':'#bbb',borderRadius:14}} onPress={()=>q.type==='multi'?toggleMulti(q.id,o.value):set(q.id,q.type==='boolean'?o.value==='yes':o.value)}><Text>{selected?'✓ ':''}{o.label}</Text></TouchableOpacity>})}<Text>Why asked: {current.whyAsked.join(' ')}</Text><View style={{flexDirection:'row',justifyContent:'space-between'}}><TouchableOpacity onPress={()=>set(q.id,SKIPPED_ANSWER)}><Text>Skip / don't know</Text></TouchableOpacity><TouchableOpacity disabled={value===undefined} onPress={()=>plan.remaining<=1?setDone(true):undefined}><Text style={{fontWeight:'700'}}>Continue</Text></TouchableOpacity></View></ScrollView></SafeAreaView>;
}
